/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package science.expo.project;

/**
 *
 * @author hsavaryjackson
 */

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import science.expo.project.util.FileUtils;
import science.expo.project.util.SpectrogramReader;


public class Main extends javax.swing.JFrame {

    public Main() {
	initComponents();
	setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFile = new javax.swing.JButton();
        pnlParameters = new javax.swing.JPanel();
        edtRange = new javax.swing.JTextField();
        edtFirstEcho = new javax.swing.JTextField();
        edtSecondEcho = new javax.swing.JTextField();
        lblValidRange = new javax.swing.JLabel();
        lblEchoOne = new javax.swing.JLabel();
        lblEchoOne1 = new javax.swing.JLabel();
        lblSecondsRange = new javax.swing.JLabel();
        lblSecondsEcho1 = new javax.swing.JLabel();
        lblSecondsEcho2 = new javax.swing.JLabel();
        btnScatterPoints = new javax.swing.JButton();
        btnImg = new javax.swing.JButton();
        lblScatterPlot = new javax.swing.JLabel();
        lblSpectrogram = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Science Expo Project program\n");
        setResizable(false);

        btnFile.setText("choose File");
        btnFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileActionPerformed(evt);
            }
        });

        pnlParameters.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblValidRange.setText("Valid Range:");

        lblEchoOne.setText("Time of first echo:");

        lblEchoOne1.setText("Time of second echo");

        lblSecondsRange.setText("s");

        lblSecondsEcho1.setText("s");

        lblSecondsEcho2.setText("s");

        javax.swing.GroupLayout pnlParametersLayout = new javax.swing.GroupLayout(pnlParameters);
        pnlParameters.setLayout(pnlParametersLayout);
        pnlParametersLayout.setHorizontalGroup(
            pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParametersLayout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEchoOne1)
                    .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblValidRange, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblEchoOne, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(60, 60, 60)
                .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edtRange)
                    .addComponent(edtFirstEcho)
                    .addComponent(edtSecondEcho, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSecondsRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecondsEcho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSecondsEcho2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        pnlParametersLayout.setVerticalGroup(
            pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParametersLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValidRange)
                    .addComponent(lblSecondsRange))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edtFirstEcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEchoOne)
                    .addComponent(lblSecondsEcho1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlParametersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edtSecondEcho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSecondsEcho2))
                    .addComponent(lblEchoOne1))
                .addGap(25, 25, 25))
        );

        btnScatterPoints.setText("get Scatter Points");
        btnScatterPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScatterPointsActionPerformed(evt);
            }
        });

        btnImg.setText("Choose Image");
        btnImg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgActionPerformed(evt);
            }
        });

        lblScatterPlot.setText("Scatter plot:");

        lblSpectrogram.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSave.setText("Save to file");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSpectrogram, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(lblScatterPlot)
                            .addGap(349, 349, 349)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pnlParameters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnScatterPoints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnFile, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnImg, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(102, 102, 102))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(btnFile, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnImg, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnScatterPoints, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlParameters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblScatterPlot, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(lblSpectrogram, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileActionPerformed
	JFileChooser fileChooser = new JFileChooser();
	if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
	    try {
		filePath = fileChooser.getSelectedFile().toURI().toURL();
		System.out.println(filePath.toExternalForm());
		
	    } catch (MalformedURLException ex) {
		Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}
    }//GEN-LAST:event_btnFileActionPerformed

    private void btnScatterPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScatterPointsActionPerformed
	try{
	    //getting input parameters
	    sRange = Double.parseDouble(edtRange.getText());
	    sEcho1 = Double.parseDouble(edtFirstEcho.getText());
	    sEcho2 = Double.parseDouble(edtSecondEcho.getText());
	    System.out.println("sRange:" + sRange);
	    System.out.println("echo1:" + sEcho1);
	    System.out.println("echo2:" + sEcho2);
	    
	} catch (NumberFormatException nfe){
	    // try catch for incorrectly enterting a double value
	    System.out.println(nfe.getMessage());
	}
	try {
	    //create the SpectrogramReader object with the given file and parameters
	    specReader = new SpectrogramReader(filePath,sEcho1,sEcho2,sRange);
	    
	    createSpecImage(fileImage);
	    
	    Graphics2D g2d = SpectrogramBuff.createGraphics();
	    
	    //draw the first echo's scatter points
	    g2d.setColor(Color.RED);
	    for (double[] sc : specReader.echoScatter1){
		double x = sc[0]/specReader.tLength * SpectrogramBuff.getWidth();
		double y = (1 - (sc[1]/specReader.fLength)) * SpectrogramBuff.getHeight();
		
		g2d.fillOval((int)x, (int)y, 4, 4);
	    }
	    
	    //draw the second echo's scatter points
	    g2d.setColor(Color.ORANGE);
	    for (double[] sc : specReader.echoScatter2){
		double x = sc[0]/specReader.tLength * SpectrogramBuff.getWidth();
		double y = SpectrogramBuff.getHeight() - (sc[1]/specReader.fLength) * SpectrogramBuff.getHeight();
		
		g2d.fillOval((int)x, (int)y, 4, 4);
	    }
	    
	    //draw the chosen starting points for each echo
	    g2d.setColor(Color.PINK);
	    double x1 = (specReader.tEcho1 + specReader.t1)/specReader.tLength * SpectrogramBuff.getWidth();
	    double x2 = (specReader.tEcho2 + specReader.t1)/specReader.tLength * SpectrogramBuff.getWidth();
	    
	    g2d.fillOval((int)x1, 0, 6, 6);
	    g2d.fillOval((int)x2, 0, 6, 6);
	    
	    g2d.dispose();
	    
	    lblSpectrogram.setIcon(new ImageIcon(SpectrogramBuff));
	    repaint();
	    
	} catch (URISyntaxException ex) {
	    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	} catch (IOException ex) {
	    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	}
    }//GEN-LAST:event_btnScatterPointsActionPerformed

    //used when setting the spectrogram BufferedImage
    private void createSpecImage(URL url) throws IOException{
	Image img = ImageIO.read(url).getScaledInstance(lblSpectrogram.getWidth(), lblSpectrogram.getHeight(), Image.SCALE_SMOOTH); 
		
	if (SpectrogramBuff == null){
	    SpectrogramBuff = new BufferedImage(lblSpectrogram.getWidth(),lblSpectrogram.getHeight(), BufferedImage.TYPE_INT_ARGB);
	}
		
	Graphics2D g2d = SpectrogramBuff.createGraphics();
	g2d.drawImage(img, 0,0, null);
	g2d.dispose();
    }
	    
    private void btnImgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgActionPerformed
	JFileChooser fileChooser = new JFileChooser();
	if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
	    try {
		fileImage = fileChooser.getSelectedFile().toURI().toURL();
		System.out.println(fileImage.toExternalForm());
		
		createSpecImage(fileImage);
		
		lblSpectrogram.setIcon(new ImageIcon(SpectrogramBuff));
		repaint();
		
	    } catch (MalformedURLException ex) {
		Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	    } catch (IOException ex) {
		Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
	    }
	}
    }//GEN-LAST:event_btnImgActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser fileChooser = new JFileChooser();
	
	fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
	fileChooser.setAcceptAllFileFilterUsed(false);
	
	if(fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION){
	    String dir = fileChooser.getSelectedFile().getAbsolutePath() + File.separator;
	    String echo1 = "echo1.csv";
	    String echo2 = "echo2.csv";
	    FileUtils.scatterToCSV(echo1, dir, specReader.echoScatter1);
	    FileUtils.scatterToCSV(echo2, dir, specReader.echoScatter2); 
	}
    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new Main();
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFile;
    private javax.swing.JButton btnImg;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnScatterPoints;
    private javax.swing.JTextField edtFirstEcho;
    private javax.swing.JTextField edtRange;
    private javax.swing.JTextField edtSecondEcho;
    private javax.swing.JLabel lblEchoOne;
    private javax.swing.JLabel lblEchoOne1;
    private javax.swing.JLabel lblScatterPlot;
    private javax.swing.JLabel lblSecondsEcho1;
    private javax.swing.JLabel lblSecondsEcho2;
    private javax.swing.JLabel lblSecondsRange;
    private javax.swing.JLabel lblSpectrogram;
    private javax.swing.JLabel lblValidRange;
    private javax.swing.JPanel pnlParameters;
    // End of variables declaration//GEN-END:variables
    public double sRange;
    public double sEcho1;
    public double sEcho2;
    public URL filePath;
    public URL fileImage;
    public BufferedImage SpectrogramBuff;
    SpectrogramReader specReader ;
    
}

